### ISSUE TITLE
Crossed, Nested, and Crossed & Nested structures; Additional sampling tree levels

### ISSUE THREAD

**Issue by carowjp** [jgherruzo/pyPETB#39]
Hello and nice work.

From looking at the code I believe the 'classical' gage R&R is implemented, where each operator measures the same set of parts, so measurement is nested under part, and part and operator are crossed.

Do you have any plans to support a fully nested sampling plan where each operator measures their own set of parts (mentioned in the article you referenced as a case in destructive testing)?

Additionally, it would be great to be able to analyze the variance components for a larger sampling plan. A simple example: each operator uses two gages, so parts are crossed with gages, and gages are crossed with operators.

![image](https://github.com/jgherruzo/pyPETB/assets/6192645/275bf701-cc51-4715-9b37-2840f7a31beb)

**Comment by jgherruzo** [comment]
Hi Jim,

thank you very much for your comment.

You are rigth, current algorithm is based on crossed analysis. Nested one was not in the roadmap but if it is interesting for the users I'll include in the next 0.3.0 milestone.

Regarding last topic, may I'll be wrong, but if we have all measurement in a dataframe, I would split it in two, one per gage. Then, I would run one analysis per gage. Variability added by Operators must be the same, so we could check if each gage add different variability. Will it work?

**Comment by carowjp** [comment]
Hello,

Nested is not so critical as is primarily for those doing destructive testing.

Your suggestion could work to some extent but couldn't directly quantify the interactions between gage and other effects. I'm inspired to start working on some code.

Best, Jim

**Comment by jgherruzo** [comment]
After some test I could check that this kind of processes where the sample is destroyed could be analyzed using the existing repeatability module. It was developed for automatic measurement system, where operator doesn't add variability to the system and reproducibility analysis is not required. 

I tested some web datasets and result given by repeatability module match with the source of the data.

Thanks¡
